### ISSUE TITLE
Save to local docker cache for reuse outside of pulumi

### ISSUE THREAD

**Issue by ShedPlant** [pulumi/pulumi-docker-build#99]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

My CICD workflow is:
1. `pulumi up` with `pulumi-docker-build` `Image` to build and push to AWS ECR
2. `docker compose up` with the application just built and deployed by `pulumi up`, run some tests.

I expected the tests run in step 2 to reuse the pulled/cached/built images from step 1.
I think this was the behaviour in `pulumi-docker` (not `-build`).

However, I can see that the image built by pulumi is not available on the host with repro steps:
1. `docker system prune -a`
2. `docker images --all`
3. `pulumi up` with a project with a `Image` resource.
4. `docker images --all` does not include the image which was just built.

The problem is that to run my tests I need to pull or build them again, which takes time that seems unnecessary.

If I'm missing some option for this to work, please point it out since it wasn't clear to me 🙏 .

```python
docker_build.ImageArgs(
            context=docker_build.BuildContextArgs(
                location=str(MONOREPO_ROOT),
            ),
            dockerfile=docker_build.DockerfileArgs(
                    location=str(PROJECT_DIR / "service.Dockerfile")
            ),
            cache_from=[
                docker_build.CacheFromArgs(
                    registry=docker_build.CacheFromRegistryArgs(
                        ref=self.repo.repository_url.apply(
                            lambda repository_url: f"{repository_url}:cache"
                        ),
                    )
                )
            ],
            cache_to=[
                docker_build.CacheToArgs(
                    registry=docker_build.CacheToRegistryArgs(
                        image_manifest=True,
                        oci_media_types=True,
                        ref=self.repo.repository_url.apply(
                            lambda repository_url: f"{repository_url}:cache"
                        ),
                    )
                )
            ],
            registries=[
                docker_build.RegistryArgs(
                    address=self.repo.repository_url,
                    username=auth_token.user_name,
                    password=auth_token.password,
                )
            ],
            tags=[
                self.repo.repository_url.apply(
                    lambda repository_url: f"{repository_url}:latest"
                ),
                self.repo.repository_url.apply(
                    lambda repository_url: f"{repository_url}:{_git_sha}"
                ),
            ],
            push=push,
        )
```

**Comment by blampe** [comment]
Hi @ShedPlant, the `docker-build` provider shares the same behavior as `docker buildx build` and doesn't load tags into the Docker daemon by default. This needs to be requested explicitly -- `--load` on the CLI, or `load=true` in the provider.

However since you're already pushing to a registry you won't be able to also load into Docker until https://github.com/pulumi/pulumi-docker-build/issues/21 is resolved.

In the meantime your cache tag _should_ work as long as your compose file has a [`cache_to`](https://docs.docker.com/compose/compose-file/build/#cache_from) pointing to it (and your build context hasn't changed between the initial registry push and your `compose up`). If your registry location isn't predictable, you can configure CI to also export to a local directory and use that directory in your compose file.

**Comment by ShedPlant** [comment]
Thanks.
For now I have indeed put `cache_from` into `docker-compose.yml` and make sure to `docker compose pull` before running tests.

Hopefully in future I can replace the pull with `load` parameter.
